### ISSUE TITLE
Your app crashed

### ISSUE THREAD

**Issue by rvsharpe** [noam09/ulauncher-gnome-control-center#4]
Message: 'com.github.noam09.ulauncher-gnome-control-center'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 436, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.noam09.ulauncher-gnome-control-center'

```

**Comment by noam09** [comment]
Hey @rvsharpe, it seems like this may be an issue Ulauncher is having with the initial loading of the extension.
Can you please try relaunching Ulauncher with debugging enabled and post a full log?
